// Every number quoted in README.md, checked against the file it came from.
//
// The tables under docs/ are regenerated by code. The prose around them is
// typed by hand, and it repeats about twenty of those numbers in sentences.
// Nothing connected the two, so a table could be regenerated and the paragraph
// above it left describing the old run, which is the failure mode a reader is
// least able to catch: the sentence looks like evidence and the table it
// contradicts is two screens away.
//
// This does not scrape numbers out of the README and hope. Each claim below is
// computed from the source file first, rendered at the precision the README
// uses, and then required to appear in the README in its own sentence. So it
// fails if the data moves, and it fails if the prose is edited away from the
// data.
//
// Run: node verify/readme_audit.js <repo root>

'use strict';

const fs = require('fs');
const path = require('path');

const root = process.argv[2] || '.';
const read = (...p) => fs.readFileSync(path.join(root, ...p), 'utf8');

// The README is reflowed prose, so a claim can straddle a line break.
const readme = read('README.md').replace(/\s+/g, ' ');

const COLUMNS = ['return', 'served', 'dropped', 'peak_q', 'mean_q', 'churn'];

// One of the fixed width tables under docs/: a label followed by six numbers.
function readTable(rel) {
    const rows = {};
    for (const line of read(...rel.split('/')).split('\n')) {
        const fields = line.trim().split(/\s+/);
        if (fields.length < 7) continue;
        const tail = fields.slice(-6).map(Number);
        if (tail.some(Number.isNaN)) continue;
        const label = fields.slice(0, -6).join(' ');
        if (label) rows[label] = Object.fromEntries(COLUMNS.map((c, i) => [c, tail[i]]));
    }
    return rows;
}

// docs/transfer.txt: grid, nodes, edges, then served and peak_q for three policies.
function readTransfer() {
    const rows = [];
    for (const line of read('docs', 'transfer.txt').split('\n')) {
        const f = line.trim().split(/\s+/);
        if (f.length !== 9 || !/^\d+x\d+$/.test(f[0])) continue;
        const n = f.slice(1).map(Number);
        if (n.some(Number.isNaN)) continue;
        rows.push({
            grid: f[0], nodes: n[0], edges: n[1],
            served: { sp: n[2], bp: n[3], ppo: n[4] },
            peak: { sp: n[5], bp: n[6], ppo: n[7] },
        });
    }
    return rows;
}

function readCsv(rel) {
    const lines = read(...rel.split('/')).trim().split('\n');
    const header = lines[0].split(',');
    return lines.slice(1).map((l) => {
        const f = l.split(',');
        return Object.fromEntries(header.map((h, i) => [h, f[i]]));
    });
}

const ablations = readTable('docs/ablations.txt');
const transfer = readTransfer();
const anatomy = Object.fromEntries(
    readCsv('verify/data/reward-anatomy.csv').map((r) => [r.term, Number(r.cumulative)])
);
const tensors = Object.fromEntries(
    readCsv('verify/data/transfer-tensors.csv').map((r) => [r.kind, r])
);
const episodes = readCsv('verify/data/episode-metrics.csv');

const agent = ablations['ppo 4M'];
const bp = ablations['backpressure'];
const baseline400k = ablations['ppo 400k (baseline)'];
const gain = ablations['ppo 400k gain 1.0'];
const entropy = ablations['ppo 4M entropy'];

const f = (x, d) => x.toFixed(d);
const margin = (r) => r.served.ppo - r.served.bp;
const byMargin = [...transfer].sort((a, b) => margin(a) - margin(b));
const widest = byMargin[byMargin.length - 1];
const narrowest = byMargin[0];
const biggest = transfer[transfer.length - 1];
const trained = transfer.find((r) => r.grid === '4x5');
const copied = Number(tensors.copied.count);
const skipped = Number(tensors.skipped.count);
const skippedNames = tensors.skipped.names.split(' ');
const perPolicy = {};
for (const row of episodes) perPolicy[row.policy] = (perPolicy[row.policy] || 0) + 1;
const episodeCount = Math.max(...Object.values(perPolicy));
const checkpointMiB = fs.statSync(
    path.join(root, 'checkpoints', 'ppo-gnn-4m.zip')
).size / 1048576;
const anatomyRatio = anatomy.throughput / anatomy.congestion;

// Each entry: what the number means, where it comes from, and the sentence the
// README has to contain once that number is rendered.
const claims = [
    ['served, agent against backpressure', 'docs/ablations.txt',
        `${f(agent.served, 3)} served against ${f(bp.served, 3)}`],
    ['dropped, agent against backpressure', 'docs/ablations.txt',
        `${f(agent.dropped, 3)} dropped against ${f(bp.dropped, 3)}`],
    ['peak backlog, agent against backpressure', 'docs/ablations.txt',
        `${f(agent.peak_q, 3)} mean peak backlog against ${f(bp.peak_q, 3)}`],
    ['mean backlog, the metric it loses', 'docs/ablations.txt',
        `mean backlog over all nodes is ${f(agent.mean_q, 3)} against ${f(bp.mean_q, 3)}`],
    ['mean backlog, restated in section 2.1', 'docs/ablations.txt',
        `the column it loses, ${f(agent.mean_q, 3)} against ${f(bp.mean_q, 3)}`],
    ['served, restated in section 2.1', 'docs/ablations.txt',
        `serves ${f(agent.served, 3)} of offered demand against backpressure's ${f(bp.served, 3)}`],
    ['dropped, restated in section 2.1', 'docs/ablations.txt',
        `drops ${f(agent.dropped, 3)} against ${f(bp.dropped, 3)}`],
    ['peak backlog, restated in section 2.1', 'docs/ablations.txt',
        `holds the worst node at ${f(agent.peak_q, 3)} against ${f(bp.peak_q, 3)}`],
    ['churn, agent against backpressure', 'docs/ablations.txt',
        `churn is ${f(agent.churn, 4)} against backpressure's ${f(bp.churn, 4)}`],
    ['the gain 1.0 ablation and its baseline', 'docs/ablations.txt',
        `(${f(gain.served, 3)} served, ${f(gain.peak_q, 3)} peak backlog against the 400k `
        + `baseline's ${f(baseline400k.served, 3)} and ${f(baseline400k.peak_q, 3)})`],
    ['the entropy ablation', 'docs/ablations.txt',
        `entropy bonus at 4M gave ${f(entropy.served, 3)} served against the plain run's `
        + `${f(agent.served, 3)}`],
    ['transfer to the largest grid', 'docs/transfer.txt',
        `on ${biggest.grid}`],
    ['served on the largest grid', 'docs/transfer.txt',
        `serves ${f(biggest.served.ppo, 3)} against backpressure's ${f(biggest.served.bp, 3)}`],
    ['peak backlog on the largest grid', 'docs/transfer.txt',
        `peak backlog at ${f(biggest.peak.ppo, 3)} against ${f(biggest.peak.bp, 3)}`],
    ['how much bigger the largest grid is', 'docs/transfer.txt',
        `${f(biggest.edges / trained.edges, 1)} times the edges`],
    ['the widest served margin, and where', 'docs/transfer.txt',
        `widest served gap is +${f(margin(widest), 3)} on the ${widest.grid} grid`],
    ['the narrowest served margin, and where', 'docs/transfer.txt',
        `narrowest is +${f(margin(narrowest), 3)} on ${narrowest.grid}`],
    ['the served margin it comes back to', 'docs/transfer.txt',
        `back to +${f(margin(biggest), 3)} on ${biggest.grid}`],
    ['tensors that survive a change of topology', 'verify/data/transfer-tensors.csv',
        `${copied} of ${copied + skipped} tensors copy across a change of topology`],
    ['the same count, restated in section 2.2', 'verify/data/transfer-tensors.csv',
        `copies ${copied} of its ${copied + skipped} tensors`],
    ['throughput and shaping over one episode', 'verify/data/reward-anatomy.csv',
        `throughput accumulates ${f(anatomy.throughput, 1)} of return while the shaping `
        + `term sums to ${f(anatomy.congestion, 2)}`],
    ['episodes behind every mean', 'verify/data/episode-metrics.csv',
        `${episodeCount} eval episodes`],
    ['the committed checkpoint', 'checkpoints/ppo-gnn-4m.zip',
        `ppo-gnn-4m.zip\` (${f(checkpointMiB, 1)} MB)`],
];

let failures = 0;
console.log('README.md claims, each rebuilt from its source file');
for (const [label, source, phrase] of claims) {
    const found = readme.includes(phrase);
    if (!found) failures++;
    console.log(`  ${found ? 'ok  ' : 'FAIL'} ${label.padEnd(42)} ${source}`);
    if (!found) console.log(`       README does not contain "${phrase}"`);
}

// Two claims that are about a set rather than a single number.
const named = skippedNames.every((n) => /edge_index|log_std/.test(n));
if (!(skipped === 4 && named && /the four that do not are `edge_index` buffers and `log_std`/.test(readme))) {
    console.log(`  FAIL the README names the tensors that do not transfer, and the census says: `
        + skippedNames.join(' '));
    failures++;
} else {
    console.log(`  ok   the ${skipped} skipped tensors are exactly the ones the README names`
        + `      verify/data/transfer-tensors.csv`);
}

const ratioOk = Math.abs(anatomyRatio - 400) / 400 <= 0.05
    && /a factor of about 400/.test(readme);
if (!ratioOk) {
    console.log(`  FAIL "a factor of about 400": the fixture says ${anatomyRatio.toFixed(0)}`);
    failures++;
} else {
    console.log(`  ok   throughput over shaping is ${anatomyRatio.toFixed(0)}, within 5% of the `
        + `"about 400" the README claims`);
}

console.log('');
if (failures > 0) {
    console.log(`JavaScript: ${failures} README claim(s) do not match the files they came from`);
    process.exit(1);
}
console.log(`JavaScript: all ${claims.length + 2} numbers quoted in README.md match their source files`);
