#!/usr/bin/env bash
# Recompute what this repository publishes, in every language installed here,
# and require the answers to agree.
#
# Every number in the README came out of one implementation: numpy, by way of
# dgno/simulator.py and dgno/baselines.py. The tests in tests/ check that code
# against itself, so a wrong dynamics that the tests share would survive all of
# them. These are independent implementations, and a mistake would have to be
# reproduced identically in each to go unnoticed.
#
# verify/data/ is the fixture they read: the per episode metrics behind every
# published mean, and the random draws each episode was built from, so a
# simulator in another language can replay the same network without numpy. It is
# regenerated by verify/export.py and CI requires it to come back byte identical.
#
# Each check is skipped with a message if its toolchain is missing, so a partial
# install still runs the rest. CI has all of them.
set -uo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root"
tmp="${TMPDIR:-/tmp}"

pass=0 fail=0 skip=0

run () {
    local name="$1" tool="$2"; shift 2
    printf '\n=== %s ===\n' "$name"
    if ! command -v "$tool" >/dev/null 2>&1; then
        printf 'skipped: %s is not installed\n' "$tool"
        skip=$((skip + 1)); return
    fi
    if "$@"; then pass=$((pass + 1)); else fail=$((fail + 1)); fi
}

# SQL has no assertion of its own, so the comparison lives here. Both sides are
# reduced to "label|six numbers" first: sqlite quotes the labels that contain a
# space and the printed table pads them, and neither is a disagreement.
check_sql () {
    local a b
    a=$(sqlite3 -init verify/summary.sql :memory: "" 2>/dev/null \
        | tr -d '"' \
        | awk -F, 'NF==8 {printf "%s|%s|%s|%s|%s|%s|%s\n",$1,$2,$3,$4,$5,$6,$7}' \
        | sort)
    b=$(awk 'NF>=7 {
                 n = NF - 6
                 label = $1; for (i = 2; i <= n; i++) label = label " " $i
                 v = ""; ok = 1
                 for (i = n + 1; i <= NF; i++) {
                     if ($i !~ /^-?[0-9]+\.[0-9]+$/) { ok = 0; break }
                     v = v "|" $i
                 }
                 if (ok) print label v
             }' docs/ablations.txt | sort)
    if [ -z "$a" ]; then echo "SQL produced no rows"; return 1; fi
    if [ "$a" = "$b" ]; then
        echo "SQL reproduces all $(printf '%s\n' "$a" | wc -l | tr -d ' ') rows of"\
             "docs/ablations.txt from the per episode metrics"
        return 0
    fi
    echo "SQL disagrees with the published table:"
    diff <(printf '%s\n' "$a") <(printf '%s\n' "$b") | head -20
    return 1
}

check_c () {
    cc -std=c99 -O2 -Wall -Wextra -Wpedantic -Werror \
       -o "$tmp/dgno-simulate" verify/simulate.c -lm || return 1
    "$tmp/dgno-simulate" "$root"
}

check_go () { ( cd verify/gocheck && go run . -root "$root" ); }

check_rust () { ( cd verify/permute && cargo run --release --quiet -- "$root" ); }

run "SQL, the published means"       sqlite3 check_sql
run "C, the simulator itself"        cc      check_c
run "Go, files and cross table"      go      check_go
run "R, paired inference"            Rscript Rscript verify/verify.R "$root"
run "Rust, exact randomisation test" cargo   check_rust
run "JavaScript, the README prose"   node    node verify/readme_audit.js "$root"

printf '\n%s\n' "----------------------------------------"
printf '%d passed, %d failed, %d skipped\n' "$pass" "$fail" "$skip"
[ "$fail" -eq 0 ] || exit 1
[ "$pass" -gt 0 ] || { echo "nothing ran"; exit 1; }
